config/routes.rb
Digital55::Application.routes.draw do

  match "/auth/:provider/callback" => "sessions#create"
  match "/admin"   => "sessions#admin",   :as => :admin
  match "/signout" => "sessions#destroy", :as => :signout

  match '/tags/search',     :to => "tags#search"
  match '/players/next',    :to => "players#next"

  resources :shows do
    get 'query', :on => :collection
    get 'image', :on => :member
  end

  resources :feeds do
    get 'latest', :on => :member
  end

  resources :videos

  root :to => "players#play"
end

app/models/feed.rb
class Feed < ActiveRecord::Base

  validates  :name, :uniqueness => true, :presence => true

  has_many :videos, :autosave => true, :inverse_of => :feed do
    def add_youtube_video(y)
      build.tap { |t| t.assign_youtube_attributes(y) }
    end
  end

  def latest
    self.class.transaction do
      crawler = Crawler.new(self)

      begin
        logger.info "processing page: #{crawler.page}"
        crawler.crawl
        crawler.process!
      end while crawler.next!

      self.processed = true
      save
    end
  end

  def add_youtube_video(youtube)
    !Video.know?(youtube) && videos.add_youtube_video(youtube)
  end

  def already_added?(youtube_ids)
    videos.where(:youtube_id => youtube_ids).count > 0
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  layout 'admin'

  before_filter :ensure_logged_in
  before_filter :ensure_admin_logged_in
  before_filter :set_current_videos_path, :only => [ :show, :edit ]

  # GET /feeds
  # GET /feeds.xml
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.xml
  def show
    @feed = Feed.find(params[:id])
    @search = @feed.videos.search(params[:search])
    @videos = @feed.videos.unapproved.paginate(:page => params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.xml
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/1/latest
  def latest
    @feed = Feed.find(params[:id])
    @feed.latest

    respond_to do |format|
      format.js { render :json => @feed.videos.count }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
    @search = @feed.videos.search(params[:search])
    @videos = @feed.videos.paginate(:page => params[:page], :per_page => 10)
  end

  # POST /feeds
  # POST /feeds.xml
  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to(feeds_url, :notice => 'Feed was successfully created.') }
        format.xml  { render :xml => @feed, :status => :created, :location => @feed }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.xml
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to(current_videos_path || @feed, :notice => 'Feed was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.xml
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to(feeds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= button_to 'Feeds List', feeds_path, :method => :get %>

<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% @feed.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="form_demo">
    <tbody>
      <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th> 
          <%= f.label :processed,'Need to retrieve old videos' %>
        </th>
        <td>
          <%= f.check_box :processed, {}, true, false %>
        </td>
      </tr>
      <tr>
        <th>
        </th>
        <td>
          <%= f.submit %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render :partial => "/videos/table", :locals => { 
  :search => @search, :videos => @videos 
} %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<table class="form_demo">
  <thead class="ui-widget-header">
    <tr>
      <th> User Name</th>
      <th> Number Videos </th>
      <th> Last Retrieved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody class="ui-widget-content">

    <% @feeds.each do |feed| %>
      <tr>
        <td><%= link_to feed.name, feed %></td>
        <td><%= content_tag(:span, feed.videos.count, :class => "feed_counter") %></td>
        <td><%= link_to feed.updated_at.strftime("%d %b, %Y"), feed %></td>
        <td><%= button_to 'Latest', latest_feed_path(feed), :remote => true, :method => :get %></td>
        <td><%= button_to 'Edit', edit_feed_path(feed), :method => :get %></td>
        <td><%= button_to 'Destroy', feed, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<%= button_to 'New Feed', new_feed_path, :method => :get %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => "/videos/table", :locals => { :search => @search, :videos => @videos }%>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>