config/routes.rb
Digital55::Application.routes.draw do

  match "/auth/:provider/callback" => "sessions#create"
  match "/admin"   => "sessions#admin",   :as => :admin
  match "/signout" => "sessions#destroy", :as => :signout

  match '/tags/search',     :to => "tags#search"
  match '/players/next',    :to => "players#next"

  resources :shows do
    get 'query', :on => :collection
    get 'image', :on => :member
  end

  resources :feeds do
    get 'latest', :on => :member
  end

  resources :videos

  root :to => "players#play"
end

app/models/video.rb
class Video < ActiveRecord::Base

  acts_as_taggable

  attr_accessor   :show_name
  attr_accessor   :url

  serialize  :keywords

  belongs_to :show
  belongs_to :feed,   :inverse_of => :videos

  validates_presence_of   :name
  validates_presence_of   :youtube_id, :language, :quality, :kind, :if => :approved?
  validates_uniqueness_of :youtube_id, :allow_nil => true

  validates :quality,  :inclusion => { :in => %w(hd high medium low), :allow_nil => true }, :if => :approved?
  validates :language, :inclusion => { :in => %w(telugu hindi), :allow_nil => true }, :if => :approved?
  validates :kind,     :inclusion => { :in => %w(lyric song movie trailer spoof), :allow_nil => true }, :if => :approved?

  validate  :validate_show_name
  validate  :verify_youtube_url_given,     :if => :url

  before_validation :extract_from_youtube, :if => :url

  before_save :disapprove,  :if     => :deleted?
  before_save :tag_changed, :if     => :approved?
  before_save :remove_tags, :unless => :approved?

  scope :alive,       where(:deleted  => false)
  scope :deleted,     where(:deleted  => true )
  scope :approved,    where(:approved => true )
  scope :unapproved,  where(:approved => false)

  scope :after,   lambda { | date | where("videos.published_at > ?", date.to_time) }
  scope :before,  lambda { | date | where("videos.published_at < ?", date.to_time) }

  def after_initialize(options = {})
    @show_name = show.try(:autocomplete_name)
  end

  def extract_from_youtube
    if video_id_from_url = extract_youtube_id
      @youtube = begin
        Crawler.client.video_by(video_id_from_url)
      rescue
        nil
      end
      if @youtube
        assign_youtube_attributes_for_known(@youtube)
        self.name ||= @youtube.title
      end
    end
  end

  def extract_youtube_id
    /youtube.com.*(?:\/|v=)(\w+)/.match(url).try(:[], 1)
  end

  def assign_youtube_attributes(youtube)
    assign_youtube_attributes_for_known(youtube).tap do |t|
      t.name = youtube.title
    end
  end

  def assign_youtube_attributes_for_known(youtube)
    logger.info "processing youtube video: #{youtube.unique_id}"

    attrs = %w(keywords racy description duration published_at view_count)
    attrs.each { |a| send("#{a}=", youtube.send(a)) }

    self.category   = youtube.categories[0].term
    self.rating     = youtube.rating.try(:average)
    self.youtube_id = youtube.unique_id
    self
  end

  def self.to_display(page)
    alive.order('published_at desc').approved.paginate(:page => page, :per_page => 50)
  end

  def self.know?(youtube)
    exists?(:youtube_id => youtube.unique_id)
  end

  def default_thumbnail
    "http://i2.ytimg.com/vi/#{youtube_id|| 'vQdQ2xnH0'}/default.jpg"
  end

  # embed url
  # http://www.youtube.com/v/zDRJoNTJKLs&feature=youtube_gdata_player
  def embed_url
    "http://www.youtube.com/v/#{youtube_id}&feature=youtube_gdata_player"
  end

  # player_url
  # http://www.youtube.com/v/zDRJoNTJKLs&autoplay=1
  def player_url
    "http://www.youtube.com/v/#{youtube_id}&autoplay=1"
  end

  def bare_url
    "http://www.youtube.com/watch?v#{youtube_id}"
  end

  def delete!
    update_attribute(:deleted, true)
  end

  def show_name=(value)
    @show_name = value
    self.show_id = Show.decode(@show_name).try(:id)
  end

  def self.containing_tag(query)
    ActsAsTaggableOn::Tag.find_by_sql(%Q{
      SELECT distinct(tags.name),tags.id FROM tags LEFT OUTER JOIN taggings ON tags.id = taggings.tag_id INNER JOIN videos ON videos.id = taggings.taggable_id WHERE (taggings.taggable_type = 'Video') AND (lower(tags.name) like '%#{query.downcase}%')
    }).map { |x| { :id => x.id, :name => x.name } }
  end

  private

  def verify_youtube_url_given
    if @url.present? && @youtube.nil?
      errors.add(:url, "invalid url")
    end
  end

  def validate_show_name
    if @show_name && show_id.nil?
      errors.add(:show_name, "Unknown show name")
    end
  end

  def tag_changed
    %w(quality language kind name).each do | attr_name |
      replace_tag(send("#{attr_name}"), send("#{attr_name}_was"))
    end

    replace_tag(show.try(:name), Show.find_by_id(show_id_was).try(:name))
  end

  def replace_tag(new_tag, old_tag)
    unless old_tag.blank?
      self.tag_list.delete(old_tag)
    end

    unless new_tag.blank?
      self.tag_list << new_tag
    end
  end

  def remove_tags
    self.tag_list = []
  end

  def disapprove
    self.approved = false
    true
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  layout 'admin'

  before_filter :ensure_logged_in
  before_filter :ensure_admin_logged_in

  def index
    @search = Video.unapproved.search(params[:search])
    @videos = Video.unapproved.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def shows
    @shows = Show.where(:name.like => "%#{params[:term]}%").map(&:name)

    respond_to do |format|
      format.js  { render :json => @shows  }
    end
  end

  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @video = Video.find(params[:id])
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html do
          redirect_to(edit_video_path(@video), :notice => 'Video was successfully created.')
        end
      else
        format.html do
          flash[:error] = 'Failed to save youtube video url.'
          render :action => 'new'
        end
      end
    end
  end

  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to current_videos_path || edit_video_path(Video.unapproved.first) }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to(videos_path) }
      format.json { head :ok }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper

  def render_video_box(video, options)
    div_for(video,  :class => options[:class], :width => options[:width], :height => options[:height],
    :link => video.youtube_id) do
    end
  end

  def render_iframe_box(video, options = {})
    options.reverse_merge! :width => 480, :height => 390
    height = options[:height]
    width = options[:width]
    %Q{<iframe title="#{video.name}" width="#{width}" height="#{height}" src="http://www.youtube.com/embed/#{video.youtube_id}" frameborder="0" allowfullscreen></iframe>}.html_safe
  end
end

app/views/videos/_cell.html.erb
<style>
  label { display:block; }
  tr { 
    border: 1px solid #CECECE;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1) inset, 0 1px 0 rgba(255, 255, 255, 0.2);
  }

  .form_demo td{
    padding-top: 20px;
    padding-right: 20px;
    padding-bottom: 20px;
  }
</style>
<%= render :partial => "/videos/#{video.youtube_id.present? ? 'with_video' : 'without_video'}", 
:locals =>  { :video => video } %>

app/views/videos/_form.html.erb
<style>
  .ui-icon
  {
    display: inline-block !important;
  }
</style>

<div class="admin-video">
  <% if @video.youtube_id %>
    <%= render_iframe_box(@video,:width=> 450,:height => 350) %> 
  <% end %>
</div>

<%= form_for(@video, :class => "edit-video") do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@video.errors.count, "error") %> 
        prohibited this feed from being saved:
      </h2>
      <ul>
        <% @video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="form_demo">
    <tbody>
      <tr>
        <th><%= f.label :name %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th><%= f.label :show_name, 'Movie' %></th>
        <td><%= f.text_field :show_name, :class => "show_name" %></td>
      </tr>
      <tr>
        <th><%= f.label :description %></th>
        <td><%= f.text_area :description, :rows => 8 %></td>
      </tr>
      <tr>
        <th><%= f.label :approved %></th>
        <td>
          <div class="groups">
            <%= f.radio_button :approved, true %>
            <%= label_tag 'video_approved_true', "Yes" %>
            <%= f.radio_button :approved, false %>
            <%= label_tag 'video_approved_false', "No" %>
          </div>
        </td>
      </tr>
      <tr>
        <th><%= f.label :language %></th>
        <td>
          <div class="groups">
            <%= f.radio_button :language, 'telugu' %>
            <%= label_tag 'video_language_telugu', "Telugu" %>
            <%= f.radio_button :language, 'hindi' %>
            <%= label_tag 'video_language_hindi', "Hindi" %>
          </div>
        </td>
      </tr>
      <tr>
        <th><%= f.label :kind, "Type" %></th>
        <td>
          <div class="groups">
            <%= f.radio_button :kind, 'movie' %>
            <%= label_tag 'video_kind_movie', "Movie" %>
            <%= f.radio_button :kind, 'song' %>
            <%= label_tag 'video_kind_song', "Video Song" %>
            <%= f.radio_button :kind, 'lyric' %>
            <%= label_tag 'video_kind_lyric', "Audio Song" %>
            <%= f.radio_button :kind, 'trailer' %>
            <%= label_tag 'video_kind_trailer', "Trailer" %>
          </div>
        </td>
      </tr>
      <tr>
        <th><%= f.label :quality %></th>
        <td>
          <div class="groups">
            <%= f.radio_button :quality, "hd" %>
            <%= label_tag 'video_quality_hd', "HD" %>
            <%= f.radio_button :quality, "high" %>
            <%= label_tag 'video_quality_high', "High" %>
            <%= f.radio_button :quality, "medium" %>
            <%= label_tag 'video_quality_medium', "Medium" %>
            <%= f.radio_button :quality, "low" %>
            <%= label_tag 'video_quality_low', "Low" %>
          </div>
        </td>
      </tr>
      <tr>
        <th>
        </th>
        <td><%= f.submit %></td>
      </tr>
    </tbody>
  </table>
<% end %>

<%= button_to 'All Videos', videos_path, :method => :get %>

app/views/videos/_table.html.erb
<table class="form_demo">
 <tbody> 
   <tr>
   </tr>
    <%= render :partial => "/videos/cell", :collection => videos, :as => :video  %>
  </tbody>
</table>

<%= will_paginate videos %>

app/views/videos/_video_big.html.erb
<div class='video'>

  <div style='padding:0;margin:0;width:100%;'>
    <div style='float:left;'>
      &larr;
      <%= link_to 'Back to videos list',
                            watch_channel_url('hi', @video.channels.first.name, :anchor => "#{@video.id}") %>
    </div>
    <div style='float:right;width:100px;'>
      <%= facebook_like(@video.id).html_safe %>
    </div>

    <% if current_user %>
      <div style='float:right;width:100px;'>
        <%= link_to 'Delete', @video, :method => :delete %>
      </div>
    <% end %>

    <div class='clear'></div>
  </div>

  <br />
  <br />
  <div>
    <%= div_for(video, :class => 'videobox', :link => video.youtube_id) do %>
    <% end %>
  </div>

  <div class="video_title" style='margin-top:10px;'> <%= video.name %> </div>
  <div class="video_title" style='margin-top:7px;'> <%= auto_link(video.description) %> </div>
</div>

app/views/videos/_video_small.html.erb
<div class='video'>
  <div class='video_embed'>
    <%= div_for(video, :width => 280, :height => 231, :class => 'small-video', :link => video.youtube_id) do %>
  <% end %>
  </div>

  <div class="video_title">
    <%= link_to video.name, video %>

    <div style='width:50px;float:right;padding-top:5px;overflow:hidden;margin-right:15px;'>
    <%= facebook_like(video).html_safe %>
  </div>
  </div>
</div>

app/views/videos/_with_video.html.erb
<%= form_for(video, :class => "edit-video") do |f| %>
  <tr>
    <td>
      <%= video.name %>
      <%= render_iframe_box(video,:width=> 250,:height => 200) %>
      <%= link_to 'Delete', video, :method => :delete, :remote => true, :title => "Delete video", :class => "delete_video ui-icon ui-icon-trash" %>
    </td>
    <td>
      <%= f.label   :approved %>
      <%= f.select  :approved , [['Disapprove',false], ['Approved', true]] %>
    </td>
    <td>
      <%= f.text_area :description, :rows => 10, :cols => 60 %>
      <%= f.submit "Save" %>
    </td>
    <td>
      <%= f.label   :quality %>
      <%= f.select  :quality, %w(hd high middle low) %>
    </td>
  </tr>
<% end %>

app/views/videos/_without_video.html.erb
<tr>
  <td>
    <%= image_tag video.default_thumbnail %>
  </td>
  <td>
    <%= video.name %>(<%= video.kind %>)
  </td>
  <td>
    <%= video.singers %>
  </td>
  <%= form_for(video, :class => "edit-video") do |f| %>
    <td>
      <%= f.label :url, "Youtube url" %>
      <%= f.text_field :url %>
    </td>
    <td>
      <%= f.submit "Save" %>
    </td>
  <% end %>
</tr>

app/views/videos/edit.html.erb
<h1>Editing video</h1>
<%= render 'form' %>
<%= link_to 'Destroy', @video, :method => :delete %>

app/views/videos/index.html.erb
<%= render :partial => "table", :locals => { 
  :search => @search, :videos => @videos 
} %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= form_for(@video, :class => "edit-video") do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@video.errors.count, "error") %> 
        prohibited this feed from being saved:
      </h2>
      <ul>
        <% @video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="form_demo">
    <tbody>
      <tr>
        <th><%= f.label :url %></th>
        <td><%= f.text_field :url %></td>
      </tr>
      <tr>
        <th>
        </th>
        <td><%= f.submit %></td>
      </tr>
    </tbody>
  </table>
<% end %>

<%= link_to 'Back', admin_path %>

app/views/videos/show.html.erb
<style>
  #channels_bar {display: none;}
  div.OverviewVideoWrapper {
    clear: both;
    min-width: 920px;
    text-align: center;
  }

  div.VideoPlayer {
    -moz-box-shadow: 0 0 15px #000000;
    background: none repeat scroll 0 0 #111111;
    border-bottom: 1px solid #000000;
    margin: 0 auto 30px;
    padding: 0 !important;
    width: 720px;
    height: 406px !important;
  }

  div.OverviewVideoWrapper h4{
    width: 720px;
    text-align: left;
    margin-left: 150px;
  }
</style>
<br />

<div class='OverviewVideoWrapper'>
  <h3> <%= @video.name %> </h3>
  <div class="VideoPlayer">
    <%= div_for(@video, :class => 'large-video', :width => 720, :height => 406, :link => @video.youtube_id) do %>
    <% end %>
  </div>
  <%= link_to "next>>", "#", :id => "next" %>
  <h4> <%= auto_link(@video.description) %> </h4>
</div>

app/views/videos/show.mobile.erb
<% content_for :title do %>
  <h1><%= @video.title %></h1>
<% end %>


<div class='video'>
  <div class='video_embed'>
    <%= div_for(@video, :width => 280, :height => 231, :class => 'videobox small', :link => @video.youtube_id) do %>
  <% end %>
  </div>
  <h2> <%= @video.title %> </h2>
  <h3> <%= @video.description %> </h3>
</div>