config/routes.rb
Digital55::Application.routes.draw do

  match "/auth/:provider/callback" => "sessions#create"
  match "/admin"   => "sessions#admin",   :as => :admin
  match "/signout" => "sessions#destroy", :as => :signout

  match '/tags/search',     :to => "tags#search"
  match '/players/next',    :to => "players#next"

  resources :shows do
    get 'query', :on => :collection
    get 'image', :on => :member
  end

  resources :feeds do
    get 'latest', :on => :member
  end

  resources :videos

  root :to => "players#play"
end

app/models/show.rb
class Show < ActiveRecord::Base

  serialize :data
  serialize :image

  has_many :songs,    :class_name => 'Video', :conditions => "videos.kind ='song'"
  has_many :lyrics,   :class_name => 'Video', :conditions => "videos.kind ='lyric'"
  has_many :movies,   :class_name => 'Video', :conditions => "videos.kind ='movie'"
  has_many :trailers, :class_name => 'Video', :conditions => "videos.kind ='trailer'"
  has_many :videos

  validates :name,     :presence => true, :uniqueness => { :scope => :language }, :unless => :new_record?
  validates :language, :presence => true, :inclusion => { :in => %w(telugu hindi) }, :unless => :new_record?

  scope :telugu, where(:language => 'telugu')
  scope :hindi,  where(:language => 'hindi')

  before_save :update_year, :if => :started_on_changed?
  before_validation :extract_show_info_from_page, :if => :url?

  scope :released_in_year, lambda { |y| where(["year(shows.started_on) = ?", y]) }

  def default_thumbnail
    "http://i2.ytimg.com/vi/#{videos.first.try(:youtube_id)}/0.jpg"
  end

  def autocomplete_name
    "#{name} (#{language} #{year})"
  end

  def self.decode(pattern)
    if match = /(.*).\((telugu|hindi).(\d*)\)/.match(pattern)
      send(match[2]).where(:name => match[1]).tap do | proxy |
        proxy.released_in_year(match[3]) unless match[3].blank?
      end.first
    end
  end

  def update_year
    self.year = started_on.try(:year)
  end

  def sync
    self.name = extract_name
    self.year = extract_year
    self.cast = extract_cast
    unless Rails.env.test?
      image_url = document.css("img.blackBdr").first.attributes["src"].value
      self.image = open(image_url).read
    end
    self.music_director = extract_music_director
    extract_songs
  end

  private

  def extract_show_info_from_page
    if new_record?
      (self.data ||= load_page(self.url)) && sync
    end
  end

  def movie_document
    @_movie ||= document.css(".dataTbl.r-rounded.grayBdr.r-shadow").first
  end

  def title_document
    @_title ||= movie_document.css("tr:nth-child(1) td.contentMainHead")
  end

  def title_and_year
    title_document.inner_text.gsub(/\t/,'').gsub(/\n/,"").strip
  end

  def extract_name
    title_and_year.match(/(\()(\d+)(\))/).pre_match.strip.gsub(/\r/,'').gsub(/\t/,'')
  end

  def extract_year
    title_and_year.match(/(\()(\d+)(\))/)[2]
  end

  def extract_cast
    movie_document.css("tr:nth-child(3) td.blackNoLine:last").map(&:text).map(&:strip).join(", ")
  end

  def extract_music_director
    movie_document.css("tr:nth-child(2) td.black a").map(&:text).join(",")
  end

  def extract_songs
    document.css(".dataTbl.clipDet").each { | song | make_song(song) }
  end

  def make_song(song)
    args = { :language => self.language }

    title = song.css(".lftFlt1 a.contentSubHead")
    id    = title.first.attributes["onclick"].value.match(/(\()(\d+)(\))/)[2]

    args.update({
      :name     => title.text,
      :singers  => song.css("#trackDetails#{id} div").first.css("a").map(&:text).join(","),
      :writer   => song.css("#trackDetails#{id} div").last.css("a").map(&:text).join(",")
    })

    songs.build(args.merge(:kind => 'song'))
  end

  def load_page(url)
    open(url).read
  end

  def document
    @document ||= Nokogiri::HTML(self.data)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  layout 'admin'

  before_filter :ensure_logged_in
  before_filter :ensure_admin_logged_in
  before_filter :set_current_videos_path, :only => [ :show, :edit ]

  def query
    @shows = Show.where(:name.like => "%#{params[:term]}%")
    respond_to do |format|
      format.js  { render :json => @shows.map(&:autocomplete_name) }
    end
  end


  # GET /shows
  # GET /shows.xml
  def index
    @shows = Show.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shows }
    end
  end

  # GET /shows/1
  # GET /shows/1.xml
  def show
    @show = Show.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @show }
    end
  end

  # GET /shows/new
  # GET /shows/new.xml
  def new
    @show = Show.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @show }
    end
  end

  def image
    @show = Show.find(params[:id])
    send_data @show.image, :type => 'image/jpg',:disposition => 'inline'
  end

  # GET /shows/1/edit
  def edit
    @show = Show.find(params[:id])
    @videos = @show.songs.paginate(:page => params[:page])
  end

  # POST /shows
  # POST /shows.xml
  def create
    @show = Show.new(params[:show])

    respond_to do |format|
      if @show.save
        format.html { redirect_to(edit_show_path(@show), :notice => 'Show was successfully created.') }
        format.xml  { render :xml => @show, :status => :created, :location => @show }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @show.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shows/1
  # PUT /shows/1.xml
  def update
    @show = Show.find(params[:id])

    respond_to do |format|
      if @show.update_attributes(params[:show])
        format.html { redirect_to(@show, :notice => 'Show was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @show.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.xml
  def destroy
    @show = Show.find(params[:id])
    @show.destroy

    respond_to do |format|
      format.html { redirect_to(shows_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% @show.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="form_demo">
    <tbody>
      <tr>
        <th><%= f.label :url, "Raga Page:" %></th>
        <td>
          <%= f.text_field :url %>
        </td>
      </tr>
      <tr>
        <th>
          <%= f.hidden_field :language,  :value => 'telugu' %>
        </th>
        <td>
          <%= f.submit %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing show</h1>
<%= link_to 'All Shows', shows_path %>
<%= render :partial => "/videos/table", :locals => { 
  :videos => @videos 
} %>

<%= link_to 'All Shows', shows_path %>

app/views/shows/index.html.erb
<ul>
  <% @shows.each do |show| %>
    <li>
      <%= image_tag url_for(:controller => "shows", :action => "image", :id => show.id) %>
      <td><%= link_to show.name, edit_show_path(show) %></td>
    </li>
  <% end %>
</ul>

<%= will_paginate @shows %>
<br />
<%= button_to 'New Show', new_show_path, :method => :get %>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<table width="100%" style="height: 100%;" cellpadding="10" cellspacing="0" border="0">
  <tbody>
    <tr>
      <th> Name </th>
      <th> Youtube </th>
    </tr>

    <% @show.videos.each do | video | %>
      <tr>
        <td> <%= link_to video.name, edit_video_path(video) %> </td>
        <% unless video.youtube_id %> 
          <%= form_for(video, :class => "edit-video") do |f| %>
            <td><%= f.label :url, "Youtube url"%></td>
            <td><%= f.text_field  :url %></td>
            <td><%= f.submit  %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>

  </tbody>
</table>


<%= link_to 'Edit', edit_show_path(@show) %>